version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgresSecret
      POSTGRES_DB: shopping_db
      TZ : Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d shopping_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"

  ktor:
    build: .
    container_name: ktor_backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8080/" ]
      interval: 30s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
